const express = require('express');
const cors = require('cors');
const app = express();
app.use(express.json());
app.use(cors());
const authRoutes = require('./src/routes/authRoutes');
const projectRoutes = require('./src/routes/projectRoutes');
const investmentRoutes = require('./src/routes/investmentRoutes');
const connectDB = require('./src/config/db');
const PORT = process.env.PORT || 5001;
connectDB();
app.use(authRoutes);
app.use(projectRoutes);
app.use(investmentRoutes);
app.listen(PORT, () => console.log(`Auth Service running on port ${PORT}`));
